services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: spendsplifbackend_web
    restart: always
    env_file:
      - ./backend/config/.env.prod
    volumes:
      - static_volume:/app/backend/config/static
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    image: spendsplifbackend_celery_worker
    restart: always
    env_file:
      - ./backend/config/.env.prod
    volumes:
      - static_volume:/app/backend/config/static
    command: celery -A backend.config worker --pool=solo --loglevel=INFO
    networks:
      - app-network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    image: spendsplifbackend_celery_beat
    restart: always
    env_file:
      - ./backend/config/.env.prod
    volumes:
      - static_volume:/app/backend/config/static
    command: celery -A backend.config beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    image: spendsplif_nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - /home/spendsplif/SpendSplifFront/dist:/usr/share/nginx/html
      - /home/spendsplif/SpendSplifFront/src/image/CreateCategory/svg/Bold:/usr/share/nginx/html/icons
      - /home/spendsplif/SpendSplifFront/src/image/WelcomePage:/usr/share/nginx/html/images/welcome
      - static_volume:/app/backend/config/static
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email spendsplif@gmail.com --agree-tos --no-eff-email -v -d spendsplif.com -d api.spendsplif.com
    networks:
      - app-network

volumes:
  static_volume:
  certbot-etc:
  certbot-www:

networks:
  app-network:
