version: '3'
services:

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - POSTGRES_DB=spendsplif
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password_default

  postgresql:
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spendsplif
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password_default
